name = "The Abyss"
author = "SettingDust"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "930e56b34a626b2fa926a52441b967d53a777a525b9edbad2dbc56afa7afcb0f"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
