name = "Setting Sun"
author = "SettingDust"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81c425941157ed7219028d6af71dce8518f75fddd891a9b2f6c24e6d0867a637"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
