name = "Setting Sun"
author = "SettingDust"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dee40f4183d72b8f00232a7792846aa2197730dfe007cc0891525e6b22919c1"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
