name = "Setting Sun"
author = "SettingDust"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "837ad9545dea9292a366f009228fa01450bf487ffecdbcdb4b6e108c89dc6964"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
datapack-folder = "config/paxi/datapacks"
